# Site settings
title: Zach Solcher
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. Software developer and technology enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zachsolcher.dev" # the base hostname & protocol for your site
twitter_username: your_twitter
github_username: zsolcher

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
